# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab63e10fcbcff81c912828a1131546f03f3913efbca12c0466d9f946a389f475110159c71242ebe9df1207b5dca48fd681ce48dd41f6617d038eb3bbec1d7cf0

test:
  secret_key_base: 82deebe4a7d4d483c0d994119bbde712d7dfb569bd14efccf9b92f1ae13acb6fa9d3b329b6b07fbb388968465628faa98b9d65a1c93594ed96a8e515575a72e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
